---
# for reference see:
# https://stackoverflow.com/questions/48423272/ansible-task-for-checking-that-a-host-is-really-offline-after-shutdown

- hosts: all
  tasks:
    - name: Shutdown host
      become: yes
      shell:
        cmd: "/usr/sbin/shutdown -c && /usr/sbin/shutdown -h now"
      async: 1
      poll: 0
    - name: Store target host ip
      set_fact:
        target_host: "{{ ansible_host }}"
    - name: wait for ssh to stop
      wait_for: "port=22 host={{ target_host }} delay=10 state=stopped timeout=60"
      delegate_to: 127.0.0.1
